### PR TITLE
Show proper love from all of us

### PR DESCRIPTION
**Pull request by sindrenm**
Restructure the last two credits/footer paragraphs in the README to reflect Hyper, cause we're all really pretty cool. :grinning: 

**Caution:** We may get a lot of tweets now. But they will be loving tweets.

### CODE REVIEW

**Comment by jgorset** [comment]
I'm Johannes, and I support this pull request.

**Comment by RamonGilabert** [comment]
:sushi:

**Comment by sindrenm** [comment]
:fish:

**Comment by RamonGilabert** [comment]
I thought it would look broken in the README but it doesn't! :scream:

**Comment by sindrenm** [comment]
Nope, Markdown's kinda chill with the newlines. :wink:

**Pull request merged**
